substitutions:
  devicename: "generator"
  upper_devicename: "Generator"
  run_pin: "16"
  stop_pin: "17"
  start_pin: "21"
  sw_pin: "22"
  dlc_tx_pin: "18"
  dlc_rx_pin: "19"

external_components:
  - source: github://blaisejarrett/Honda-Gen-ESPHome@main
    components: [ honda_gen_dlc ]


esphome:
  name: ${devicename}

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "fillthisin"

wifi:
  ssid: "fillthisin"
  password: "fillthisin"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Generator Fallback Hotspot"
    password: "generator"

captive_portal:

web_server:

binary_sensor:
  - platform: gpio
    pin: ${run_pin}
    name: "${upper_devicename} Running Light"
    id: "run_sensor"
  - platform: gpio
    pin: ${sw_pin}
    name: "${upper_devicename} Power Sw Enabled"
    id: "power_sw_sensor"

output:
  - platform: gpio
    pin: ${start_pin}
    id: "start_button"
  - platform: gpio
    pin: ${stop_pin}
    id: "stop_relay"

uart:
  rx_pin: ${dlc_rx_pin}
  tx_pin: ${dlc_tx_pin}
  baud_rate: 9600

honda_gen_dlc:
  # if the power is off it won't bother attempting to query sensor values.
  power_switch: power_sw_sensor

  battery_voltage:
    name: "${upper_devicename} Battery Voltage"
  engine_rpm:
    name: "${upper_devicename} Engine RPM"
  runtime:
    name: "${upper_devicename} Total Engine Runtime"
  cylinder_head_temperature:
    name: "${upper_devicename} Cylinder Head Temperature"
  engine_timing:
    name: "${upper_devicename} Engine Spark Timing"
  output_voltage:
    name: "${upper_devicename} Output Voltage"

  barometric_pressure:
    name: "${upper_devicename} Barometric Pressure"
  fuel_injection_time:
    name: "${upper_devicename} Fuel Injection Time"
  throttle:
    name: "${upper_devicename} Trottle Position"
  output_power:
    name: "${upper_devicename} Output Power"
  starter_count:
    name: "${upper_devicename} Starter Count"
  o2_sensor:
    name: "${upper_devicename} O2 Sensor"

  inv_master_current:
    name: "${upper_devicename} Master Inv Current"
  inv_master_temperature:
    name: "${upper_devicename} Master Inv Temperature"
  inv_master_eco:
    name: "${upper_devicename} Eco Mode"
  inv_master_power:
    name: "${upper_devicename} Master Inv Power"
  inv_master_volts:
    name: "${upper_devicename} Master Inv Voltage"

  inv_slave_current:
    name: "${upper_devicename} Slave Inv Current"
  inv_slave_temperature:
    name: "${upper_devicename} Slave Inv Temperature"
  inv_slave_power:
    name: "${upper_devicename} Slave Inv Power"

